#!/usr/bin/env bash
#bash script to configure my loadbalance to myservers

#sudo apt-get install -y --no-install-recommends software-properties-common;
#sudo add-apt-repository -y ppa:vbernat/haproxy-2.2;
sudo apt update;
sudo apt install -y haproxy=2.2.\*;
sudo ufw allow 80;
HAPROXY_CONFIG="\
frontend myfrontend
\tmode http
\tbind *:80
\tdefault_backend myservers
backend myservers
\tmode http
\tbalance roundrobin
\tserver server1 54.237.18.27:80 check
\tserver server2 34.232.66.181:80 check\
";
echo -e "$HAPROXY_CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg;
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
