#!/usr/bin/env bash
#generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases -uroot -p"$1" > backup.sql
time_now=$(date +"%d-%m-%Y")
file_name="$time_now.tar.gz"
tar -caf "$file_name" backup.sql
