#!/usr/bin/env bash
#loops through 1 to 10 and print bad luck at 4
#and print good luck at 8
i="0"
while [ $i -lt 10 ];do
if [ $i = 3 ]
then
echo "bad luck"
elif [ $i = 7 ]
then
echo "good luck"
else
echo "Best School"
fi
i=$[$i+1]
done
